#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamaAndrTest.Resource", IsApplication=true)]

namespace XamaAndrTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_download = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_navigation_drawer = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int bCardioBegin = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int bCardioPause = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int bCardioStop = 2131099653;
			
			// aapt resource value: 0x7f060014
			public const int bGoToMenuActivity = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int bLogin = 2131099673;
			
			// aapt resource value: 0x7f060027
			public const int bNext = 2131099687;
			
			// aapt resource value: 0x7f06001a
			public const int bNextActivityTemp = 2131099674;
			
			// aapt resource value: 0x7f06000f
			public const int bSkip = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int bStartExercise = 2131099661;
			
			// aapt resource value: 0x7f06001f
			public const int clock = 2131099679;
			
			// aapt resource value: 0x7f06002a
			public const int downloads = 2131099690;
			
			// aapt resource value: 0x7f060016
			public const int etLogin = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int etPassword = 2131099672;
			
			// aapt resource value: 0x7f060022
			public const int exerciseList = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int leftListView = 2131099683;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06001e
			public const int llHorizontal = 2131099678;
			
			// aapt resource value: 0x7f06001c
			public const int llVertical = 2131099676;
			
			// aapt resource value: 0x7f060011
			public const int lvMark = 2131099665;
			
			// aapt resource value: 0x7f06001b
			public const int myDrawer = 2131099675;
			
			// aapt resource value: 0x7f06000e
			public const int progressBar1 = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int relativeLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060024
			public const int rightListView = 2131099684;
			
			// aapt resource value: 0x7f060006
			public const int scrollView1 = 2131099654;
			
			// aapt resource value: 0x7f060025
			public const int scrollView2 = 2131099685;
			
			// aapt resource value: 0x7f060012
			public const int svExerciseMarks = 2131099666;
			
			// aapt resource value: 0x7f06000a
			public const int svParameters = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int tlCardioParams = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int tlMarkParams = 2131099667;
			
			// aapt resource value: 0x7f06000b
			public const int tlParameters = 2131099659;
			
			// aapt resource value: 0x7f060029
			public const int tlPrepareParam = 2131099689;
			
			// aapt resource value: 0x7f060026
			public const int tvExerciseTitle = 2131099686;
			
			// aapt resource value: 0x7f060009
			public const int tvExirciseName = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int tvLogin = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int tvMarkTitle = 2131099664;
			
			// aapt resource value: 0x7f06001d
			public const int tvOccupTitle = 2131099677;
			
			// aapt resource value: 0x7f060017
			public const int tvPassword = 2131099671;
			
			// aapt resource value: 0x7f060020
			public const int tvStatus = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int tvStatusValue = 2131099681;
			
			// aapt resource value: 0x7f060008
			public const int tvTimer = 2131099656;
			
			// aapt resource value: 0x7f060028
			public const int videoView1 = 2131099688;
			
			// aapt resource value: 0x7f06000c
			public const int vvExerciseVideo = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CardioExercise = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Exercise = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ExerciseMark = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Prepare = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int action_bar = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int close_drawer = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int open_drawer = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
